### ISSUE TITLE
expo-file-system package to be installed and linked

### ISSUE THREAD

**Issue by derren7532123** [JaiDeves/AirBnB-React#1]
![whatsapp image 2018-10-26 at 8 06 01 pm](https://user-images.githubusercontent.com/43113530/47566445-5621a980-d95e-11e8-8783-52722aaaea1b.jpeg)
any solution?

**Comment by JaiDeves** [comment]
This project doesn't have expo right now, But you can easily integrate expo with this repo, Please check some tutorials.
